### ISSUE TITLE
Project Plan Document

### ISSUE THREAD

**Issue by SWalt567** [COSC310-L09/cosc310_l09_proj#2]
Things to include:

- [ ] Brief description of project
- [ ] Why we chose our SDLC
- [ ] Phases of SDLC (point form)
- [ ] WBS (might not need this because of this git project)
- [ ] Gantt Chart
- [ ] List of program limitations
- [ ] Sample output of project report
